version: '3'

services:
  nextjs-app:
    image: node:19-alpine
    container_name: nextjs-container
    env_file:
      - .env
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "80:3000"
    command: sh -c "npm install && npm run build && npm start"
